import 'package:hive_flutter/hive_flutter.dart';
import 'package:plant_disease_detector/src/features/auth/data/user_model.dart';
import 'package:plant_disease_detector/src/features/garden/data/plant_model.dart';
import 'package:plant_disease_detector/src/features/garden/data/garden_adapters.dart';

part 'local_storage_service.g.dart';

/// Service for managing local storage with Hive
class LocalStorageService {
  static const String userBoxName = 'user_box';
  static const String historyBoxName = 'history_box';
  static const String settingsBoxName = 'settings_box';
  static const String plantsBoxName = 'plants_box';
  static const String plantNotesBoxName = 'plant_notes_box';
  
  static const String currentUserKey = 'current_user';
  
  static bool _isInitialized = false;
  
  /// Initialize Hive and register adapters
  static Future<void> initialize() async {
    if (_isInitialized) return;
    
    await Hive.initFlutter();
    
    // Register adapters (generated by build_runner)
    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(UserRoleAdapter());
    }
    if (!Hive.isAdapterRegistered(1)) {
      Hive.registerAdapter(UserModelAdapter());
    }
    if (!Hive.isAdapterRegistered(2)) {
      Hive.registerAdapter(DiagnosisHistoryItemCacheAdapter());
    }
    // Garden adapters
    if (!Hive.isAdapterRegistered(3)) {
      Hive.registerAdapter(PlantModelAdapter());
    }
    if (!Hive.isAdapterRegistered(4)) {
      Hive.registerAdapter(PlantNoteAdapter());
    }
    if (!Hive.isAdapterRegistered(10)) {
      Hive.registerAdapter(WateringFrequencyAdapter());
    }
    if (!Hive.isAdapterRegistered(11)) {
      Hive.registerAdapter(NoteTypeAdapter());
    }
    
    // Open boxes
    await Hive.openBox<UserModel>(userBoxName);
    await Hive.openBox<DiagnosisHistoryItemCache>(historyBoxName);
    await Hive.openBox(settingsBoxName);
    await Hive.openBox<PlantModel>(plantsBoxName);
    await Hive.openBox<PlantNote>(plantNotesBoxName);
    
    _isInitialized = true;
    print('✅ LocalStorageService initialized');
  }
  
  /// Get user box
  static Box<UserModel> get userBox => Hive.box<UserModel>(userBoxName);
  
  /// Get history box
  static Box<DiagnosisHistoryItemCache> get historyBox => 
      Hive.box<DiagnosisHistoryItemCache>(historyBoxName);
  
  /// Get settings box
  static Box get settingsBox => Hive.box(settingsBoxName);
  
  /// Get plants box
  static Box<PlantModel> get plantsBox => Hive.box<PlantModel>(plantsBoxName);
  
  /// Get plant notes box
  static Box<PlantNote> get plantNotesBox => Hive.box<PlantNote>(plantNotesBoxName);
  
  /// Get current user
  static UserModel? get currentUser => userBox.get(currentUserKey);
  
  /// Save current user
  static Future<void> saveCurrentUser(UserModel user) async {
    await userBox.put(currentUserKey, user);
  }
  
  /// Clear current user
  static Future<void> clearCurrentUser() async {
    await userBox.delete(currentUserKey);
  }
  
  /// Clear all data (for logout)
  static Future<void> clearAll() async {
    await userBox.clear();
    await historyBox.clear();
    await settingsBox.clear();
    await plantsBox.clear();
    await plantNotesBox.clear();
  }
  
  /// Close all boxes
  static Future<void> close() async {
    await Hive.close();
    _isInitialized = false;
  }
}

/// Cached diagnosis history item for Hive storage
@HiveType(typeId: 2)
class DiagnosisHistoryItemCache extends HiveObject {
  @HiveField(0)
  final String id;
  
  @HiveField(1)
  final String diseaseId;
  
  @HiveField(2)
  final String label;
  
  @HiveField(3)
  final double confidence;
  
  @HiveField(4)
  final String localImagePath;
  
  @HiveField(5)
  final String? cloudImageUrl;
  
  @HiveField(6)
  final DateTime createdAt;
  
  @HiveField(7)
  final bool isSynced;
  
  @HiveField(8)
  final String? userId;

  DiagnosisHistoryItemCache({
    required this.id,
    required this.diseaseId,
    required this.label,
    required this.confidence,
    required this.localImagePath,
    this.cloudImageUrl,
    required this.createdAt,
    this.isSynced = false,
    this.userId,
  });

  /// Create a copy with updated fields
  DiagnosisHistoryItemCache copyWith({
    String? id,
    String? diseaseId,
    String? label,
    double? confidence,
    String? localImagePath,
    String? cloudImageUrl,
    DateTime? createdAt,
    bool? isSynced,
    String? userId,
  }) {
    return DiagnosisHistoryItemCache(
      id: id ?? this.id,
      diseaseId: diseaseId ?? this.diseaseId,
      label: label ?? this.label,
      confidence: confidence ?? this.confidence,
      localImagePath: localImagePath ?? this.localImagePath,
      cloudImageUrl: cloudImageUrl ?? this.cloudImageUrl,
      createdAt: createdAt ?? this.createdAt,
      isSynced: isSynced ?? this.isSynced,
      userId: userId ?? this.userId,
    );
  }

  /// Convert to Supabase JSON
  Map<String, dynamic> toSupabase() => {
    'id': id,
    'user_id': userId,
    'disease_id': diseaseId,
    'label': label,
    'confidence': confidence,
    'image_url': cloudImageUrl,
    'local_image_path': localImagePath,
    'created_at': createdAt.toIso8601String(),
  };

  /// Create from Supabase JSON
  factory DiagnosisHistoryItemCache.fromSupabase(Map<String, dynamic> json) {
    return DiagnosisHistoryItemCache(
      id: json['id'] as String,
      diseaseId: json['disease_id'] as String,
      label: json['label'] as String,
      confidence: (json['confidence'] as num).toDouble(),
      localImagePath: json['local_image_path'] as String? ?? '',
      cloudImageUrl: json['image_url'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
      isSynced: true,
      userId: json['user_id'] as String?,
    );
  }

  @override
  String toString() => 'DiagnosisHistoryItemCache(id: $id, label: $label, synced: $isSynced)';
}
